name: Build
on:
  schedule:
    - cron: "30 15 */15 * *"
    - timezone: "(GMT-03:00) Brasilia"

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: make
          run: make fclean re
        - name: make bonus
          run: make bonus 