name: Build

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  test_linux_gmt8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    name: Test GMT +8 on Ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Timezone to +8 (With input)
        uses: ./
        with:
          timezoneLinux: "Asia/Singapore"
      - run: npm i
      - run: npm run test