name: Build
on:
  schedule:
    - cron: "*/1 * * * *"
    - timezone: "Brazil/Sao Paulo"

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: make
          run: make fclean re
        - name: make bonus
          run: make bonus 